### ISSUE TITLE
Improve the Report this plugin link visibility

### ISSUE THREAD

**Issue by bahiirwa** [TukuToi/tukutoi-cp-directory-integration#2]
Thanks for the work on this.

I have two requests if you deem so would improve the product.

1. Increase the legibility by adjusting the contrast of the `Report this plugin` link to something darker. 20% seemed better for me.
2. Move the positioning adjacent to the contact the developer. This gives a visual hierarchy. I am also more likely to hit the report this plugin button when I want to `install now` or `more details`

![Screenshot(7)](https://user-images.githubusercontent.com/7713923/175867117-19c9e2af-24f8-45a7-b39b-816bc136f0c8.png)

**Comment by smileBeda** [comment]
@bahiirwa - 20% is less than what is currently:
`rgba(255, 0, 0, 0.31)`
vs
`rgba(255, 0, 0, 0.20)`

This would be no transparency:
`rgba(255, 0, 0, 1)`

Thus it cannot become more visible by making it even more transparent.
What did you mean with 20%?

**Comment by smileBeda** [comment]
The report this plugin link has been moved as suggested in https://github.com/TukuToi/tukutoi-cp-directory-integration/tree/1.2.0

Please test and let me know what you meant with 20% if you have time, thanks.

**Comment by bahiirwa** [comment]
> What did you mean with 20%?

I meant a bump up to `rgba(255, 0, 0, 0.51)` making it deeper red

**Comment by smileBeda** [comment]
Understood, that makes more sense
As well done on this same branch.

**Comment by bahiirwa** [comment]
Thanks,

I made a slight modification to line 107

```
<div class="desc column-description" style="margin-left: unset;">
  <p><?php echo esc_html( substr( $single_plugin->description, 0, 40 ) . '...' ); ?></p>
  <p class="authors"> 
	  <cite>By <a href="<?php echo esc_url_raw( $single_plugin->developer->web_url ); ?>"><?php echo esc_html( $single_plugin->developer->name ); ?></a></cite>
  </p>
  <p>
	  <small><a href="https://forums.classicpress.net/u/<?php echo rawurlencode( esc_html( $single_plugin->developer->username ) ); ?>"><?php esc_html_e( 'Contact the Developer', 'cp-plgn-drctry' ); ?></a></small> | 
	  <small><a style="color:rgba(255, 0, 0, 0.31);" href="mailto:plugins@classicpress.net?subject=Plugin Report for <?php echo esc_html( $single_plugin->name ); ?>&body=Please review this plugin: <?php echo esc_html( $single_plugin->name ); ?>. It has the following problems which require the ClassicPress Plugin Review Team action: {LIST THE ISSUES HERE. PLEASE ONLY USE THIS IF YOU THINK THE PLUGIN MUST BE IMMEDIATELY SUSPENDED. OTHERWISE CONTACT THE AUTHOR: https://forums.classicpress.net/u/<?php echo esc_html( $single_plugin->developer->username ); ?>}."><?php esc_html_e( 'Report this Plugin', 'cp-plgn-drctry' ); ?></a></small>
  </p>
  </div>
```

Result is might tighter reducing the whitespace. Design decision still remains yours.

![Screenshot 2022-06-27 at 12 17 41](https://user-images.githubusercontent.com/7713923/175905649-cf35edcc-d518-4e75-bcda-9e018a3a2bef.png)

**Comment by smileBeda** [comment]
Makes sense

Pushed to branch.
